package io.github.derui.pegen.core.parsing

import io.github.derui.pegen.core.support.Err
import io.github.derui.pegen.core.support.Ok
import io.github.derui.pegen.core.support.Result

/**
 * A context for parsing. This class is completely immutable.
 */
class ParserContext private constructor(
    private var currentPosition: Position,
    private val input: String,
    private val startIndex: Int,
) {
    companion object {
        fun startOf(input: String): ParserContext = ParserContext(Position.start(), input, 0)
    }

    private var currentIndex: Int = startIndex

    val position get() = currentPosition

    /**
     * Get the next character and move the cursor forward.
     * If index is reached to the end of input, return [Err] with [ErrorInfo].
     */
    fun readChar(): Result<Char, ErrorInfo> {
        if (input.length <= currentIndex) {
            return Err(ErrorInfo(listOf("Unexpected end of input"), currentPosition))
        }
        val c = input[currentIndex++]
        currentPosition = currentPosition.forward(c)

        return Ok(c)
    }

    /**
     * Get a new context with new input
     */
    fun newContext(): ParserContext = ParserContext(currentPosition, input, currentIndex)

    // / Generated by IntelliJ IDEA ///
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as ParserContext

        if (currentPosition != other.currentPosition) return false
        if (input != other.input) return false
        if (currentIndex != other.currentIndex) return false

        return true
    }

    override fun hashCode(): Int {
        var result = currentPosition.hashCode()
        result = 31 * result + input.hashCode()
        result = 31 * result + currentIndex
        return result
    }

    override fun toString(): String {
        return "ParserContext(currentPosition=$currentPosition, input='$input', currentIndex=$currentIndex)"
    }
}
